/** Type-only barrel: safe to import from anywhere, including client-reachable code — no zod runtime here. See each `*.zod.ts` sibling for the runtime shape, used only by `scripts/validate.ts`. */
export type { Localized, Locale } from './localized.ts'
export { pickLocalized, pickLocalizedList, LOCALES } from './localized.ts'
export type { ImageContent } from './image.ts'
export type { Business, SocialLink } from './business.ts'
export type { Claims } from './claims.ts'
export type { Question } from './faq.ts'
export type { ServiceId, Service, SpecSheet, SpecList } from './service.ts'
export type { Project, ExecutionSpecs } from './project.ts'
export type { Article, ArticleBlock, ParagraphBlock, HeadingBlock, OrderedListBlock, ProjectCalloutBlock, PendingBlock } from './article.ts'
export type { HomeContent, Space } from './home.ts'
