// (f) robots.txt exists, references the sitemap, and does not disallow
// known AI crawlers — the user's GEO/AEO decision (§7 of
// arquitectura-plantilla-monorepo.md, 2026-09-15). Checked against EVERY
// sitemap path, not just "/": a crawler-specific group could allow the
// site root while disallowing one subtree (e.g. "Disallow: /proyectos/"
// under a "User-agent: GPTBot" block) and a root-only probe would miss it.
import { readServerAppFile } from '../lib/manifest.mjs'

const AI_CRAWLERS = ['GPTBot', 'OAI-SearchBot', 'ClaudeBot', 'PerplexityBot', 'Google-Extended', 'CCBot']

function parseRobotsTxt(text) {
  const groups = []
  let current = null
  let sitemap = null
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.split('#')[0].trim()
    if (!line) continue
    const [rawKey, ...rest] = line.split(':')
    if (!rawKey || rest.length === 0) continue
    const key = rawKey.trim().toLowerCase()
    const value = rest.join(':').trim()
    if (key === 'user-agent') {
      if (!current || current.rules.length > 0) {
        current = { agents: [], rules: [] }
        groups.push(current)
      }
      current.agents.push(value)
    } else if (key === 'allow' || key === 'disallow') {
      if (!current) continue
      current.rules.push({ type: key, value })
    } else if (key === 'sitemap') {
      sitemap = value
    }
  }
  return { groups, sitemap }
}

/**
 * The applicable group(s) for `agent`, per RFC 9309 §2.2.1: a case-
 * insensitive match on the product token, falling back to `*`. A robots.txt
 * can legally list the SAME agent (or `*`) across more than one non-adjacent
 * block — `parseRobotsTxt` above only merges immediately-consecutive
 * `User-agent` lines into one group, by design (a blank/rule-separated
 * repeat is a distinct group at the parse level) — so every group whose
 * `agents` include a case-insensitive match is combined into one rule set
 * here, not just the first one found.
 */
function groupsFor(groups, agent) {
  const exact = groups.filter((g) => g.agents.some((a) => a.toLowerCase() === agent.toLowerCase()))
  if (exact.length > 0) return exact
  return groups.filter((g) => g.agents.includes('*'))
}

/**
 * RFC 9309 §2.2.3 pattern matching: `*` matches any sequence of characters
 * (including none), and a trailing `$` anchors the match to the end of the
 * path. Everything else in the rule is matched literally (percent-encoding
 * aside, which this repo's own robots output never uses).
 */
function ruleToRegExp(value) {
  const endAnchored = value.endsWith('$')
  const body = endAnchored ? value.slice(0, -1) : value
  const escaped = body.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')
  return new RegExp(`^${escaped}${endAnchored ? '$' : ''}`)
}

function ruleMatches(rule, testPath) {
  if (rule.value === '') return false // an empty Disallow means "allow everything"; an empty Allow matches nothing extra
  return ruleToRegExp(rule.value).test(testPath)
}

// "Specificity" for the longest-match rule (RFC 9309 §2.2.2): the length of
// the rule's own entry, ignoring a trailing `$` (an anchor isn't part of
// the matched path). On a tie, Allow wins over Disallow — the RFC asks
// implementations to prefer the least-restrictive rule when genuinely
// ambiguous, which is what every major crawler's public documentation of
// this same tie-break does in practice.
function specificity(rule) {
  return rule.value.endsWith('$') ? rule.value.length - 1 : rule.value.length
}

function isBlocked(groups, agent, testPath) {
  const applicable = groupsFor(groups, agent)
  if (applicable.length === 0) return false
  let best = null
  for (const group of applicable) {
    for (const rule of group.rules) {
      if (!ruleMatches(rule, testPath)) continue
      const score = specificity(rule)
      if (!best || score > best.score || (score === best.score && rule.type === 'allow' && best.rule.type === 'disallow')) {
        best = { score, rule }
      }
    }
  }
  return best ? best.rule.type === 'disallow' : false
}

export async function checkRobots({ nextDir, siteUrl, sitemapUrls, reporter }) {
  reporter.startCheck('(f) robots.txt: exists, references sitemap, allows AI crawlers on every sitemap path')
  const text = await readServerAppFile(nextDir, 'robots.txt.body')
  if (text === null) {
    reporter.report({ check: 'robots', code: 'missing', route: null, message: 'robots.txt was not generated by the build' })
    reporter.endCheck()
    return
  }
  const { groups, sitemap } = parseRobotsTxt(text)
  const expectedSitemap = `${siteUrl}/sitemap.xml`
  if (sitemap !== expectedSitemap) {
    reporter.report({
      check: 'robots',
      code: 'wrong-sitemap-reference',
      route: null,
      message: `robots.txt Sitemap directive is "${sitemap ?? '(none)'}", expected "${expectedSitemap}"`,
    })
  }

  // Every sitemap path, origin stripped, trailing slash kept (trailingSlash:
  // true) — plus "/" itself, which may not be a sitemap entry but is still
  // the site root a crawler starts from.
  const testPaths = new Set(['/'])
  for (const url of sitemapUrls ?? []) {
    if (url.startsWith(siteUrl)) testPaths.add(url.slice(siteUrl.length) || '/')
  }

  for (const bot of AI_CRAWLERS) {
    for (const testPath of testPaths) {
      if (isBlocked(groups, bot, testPath)) {
        reporter.report({
          check: 'robots',
          code: 'ai-crawler-disallowed',
          route: testPath,
          detail: bot,
          message: `robots.txt disallows "${bot}" on "${testPath}"`,
        })
      }
    }
  }
  reporter.endCheck()
}
