// (f) robots.txt exists, references the sitemap, and does not disallow
// known AI crawlers — the user's GEO/AEO decision (§7 of
// arquitectura-plantilla-monorepo.md, 2026-09-15).
import { readServerAppFile } from '../lib/manifest.mjs'

const AI_CRAWLERS = ['GPTBot', 'OAI-SearchBot', 'ClaudeBot', 'PerplexityBot', 'Google-Extended', 'CCBot']

function parseRobotsTxt(text) {
  const groups = []
  let current = null
  let sitemap = null
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.split('#')[0].trim()
    if (!line) continue
    const [rawKey, ...rest] = line.split(':')
    if (!rawKey || rest.length === 0) continue
    const key = rawKey.trim().toLowerCase()
    const value = rest.join(':').trim()
    if (key === 'user-agent') {
      if (!current || current.rules.length > 0) {
        current = { agents: [], rules: [] }
        groups.push(current)
      }
      current.agents.push(value)
    } else if (key === 'allow' || key === 'disallow') {
      if (!current) continue
      current.rules.push({ type: key, value })
    } else if (key === 'sitemap') {
      sitemap = value
    }
  }
  return { groups, sitemap }
}

function groupFor(groups, agent) {
  const exact = groups.find((g) => g.agents.some((a) => a.toLowerCase() === agent.toLowerCase()))
  if (exact) return exact
  return groups.find((g) => g.agents.includes('*')) ?? null
}

function isBlocked(groups, agent, testPath) {
  const group = groupFor(groups, agent)
  if (!group) return false
  let best = null
  for (const rule of group.rules) {
    if (rule.value === '') continue // an empty Disallow means "allow everything"
    if (testPath.startsWith(rule.value)) {
      if (!best || rule.value.length > best.value.length) best = rule
    }
  }
  return best ? best.type === 'disallow' : false
}

export async function checkRobots({ nextDir, siteUrl, reporter }) {
  reporter.startCheck('(f) robots.txt: exists, references sitemap, allows AI crawlers')
  const text = await readServerAppFile(nextDir, 'robots.txt.body')
  if (text === null) {
    reporter.report({ check: 'robots', code: 'missing', route: null, message: 'robots.txt was not generated by the build' })
    reporter.endCheck()
    return
  }
  const { groups, sitemap } = parseRobotsTxt(text)
  const expectedSitemap = `${siteUrl}/sitemap.xml`
  if (sitemap !== expectedSitemap) {
    reporter.report({
      check: 'robots',
      code: 'wrong-sitemap-reference',
      route: null,
      message: `robots.txt Sitemap directive is "${sitemap ?? '(none)'}", expected "${expectedSitemap}"`,
    })
  }
  for (const bot of AI_CRAWLERS) {
    if (isBlocked(groups, bot, '/')) {
      reporter.report({ check: 'robots', code: 'ai-crawler-disallowed', route: null, message: `robots.txt disallows "${bot}"` })
    }
  }
  reporter.endCheck()
}
