// (a), static half: every prerendered page (except not-found and pages
// marked noindex) is in sitemap.xml, and every sitemap URL corresponds to a
// real prerendered page. The "returns 200" half needs a live server — see
// checks/live.mjs.
import { readServerAppFile } from '../lib/manifest.mjs'

function extractLocs(xml) {
  const urls = []
  const re = /<loc>([^<]+)<\/loc>/g
  let m
  while ((m = re.exec(xml))) urls.push(m[1])
  return urls
}

export async function checkSitemapStatic({ pages, nextDir, siteUrl, reporter }) {
  reporter.startCheck('(a) sitemap: indexable pages present, no stale/foreign entries')

  const xml = await readServerAppFile(nextDir, 'sitemap.xml.body')
  if (xml === null) {
    reporter.report({ check: 'sitemap', code: 'missing-sitemap', route: null, message: 'sitemap.xml was not generated by the build' })
    reporter.endCheck()
    return []
  }
  const sitemapUrls = new Set(extractLocs(xml))
  const pageUrlByPath = new Map(pages.map((p) => [`${siteUrl}${p.publicPath}`, p]))

  for (const page of pages) {
    if (page.noindex) continue
    const url = `${siteUrl}${page.publicPath}`
    if (!sitemapUrls.has(url)) {
      reporter.report({ check: 'sitemap', code: 'missing-from-sitemap', route: page.publicPath, message: `indexable page is not listed in sitemap.xml (${url})` })
    }
  }

  for (const url of sitemapUrls) {
    if (!pageUrlByPath.has(url)) {
      reporter.report({ check: 'sitemap', code: 'not-a-real-page', route: null, message: `sitemap.xml lists "${url}", which is not a prerendered page in this build` })
    }
  }

  reporter.endCheck()
  return [...sitemapUrls]
}
